# Generated by Django 4.2.7 on 2024-01-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
