# Generated by Django 4.2.7 on 2024-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='ramen',
            name='acter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
