# Generated by Django 4.2.7 on 2024-01-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0004_delete_review_ramen_acter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramen',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ramen',
            name='staff',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
