# Generated by Django 4.2.7 on 2024-01-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='ramen',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (3, '3'), (5, '5'), (2, '2'), (4, '4'), (1, '1')]),
        ),
    ]
