# Generated by Django 4.2.7 on 2024-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0008_rename_book_review_ramen_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(3, '3'), (2, '2'), (5, '5'), (0, '0'), (1, '1'), (4, '4')]),
        ),
    ]
