# Generated by Django 4.2.7 on 2024-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0009_review_title_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(4, '4'), (1, '1'), (2, '2'), (0, '0'), (5, '5'), (3, '3')]),
        ),
    ]
