# Generated by Django 4.2.7 on 2024-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0014_future_acter_future_company_future_music_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='future',
            old_name='thumbnail',
            new_name='thumbnail_future',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(3, '3'), (2, '2'), (1, '1'), (4, '4'), (0, '0'), (5, '5')]),
        ),
    ]
