# Generated by Django 4.2.7 on 2024-01-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0015_rename_thumbnail_future_thumbnail_future_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('thumbnail_news', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (4, '4'), (3, '3'), (5, '5'), (2, '2'), (1, '1')]),
        ),
    ]
