# Generated by Django 4.2.7 on 2024-01-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0016_news_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (2, '2'), (0, '0'), (5, '5'), (1, '1')]),
        ),
    ]
