# Generated by Django 4.2.7 on 2024-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0017_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(4, '4'), (0, '0'), (5, '5'), (1, '1'), (3, '3'), (2, '2')]),
        ),
    ]
