# Generated by Django 4.2.7 on 2024-01-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0019_news_category_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('ニュース', 'ニュース'), ('特集', '特集')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (1, '1'), (4, '4'), (5, '5'), (0, '0')]),
        ),
    ]
