# Generated by Django 4.2.7 on 2024-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen', '0021_legend_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(0, '0'), (5, '5'), (2, '2'), (1, '1'), (4, '4'), (3, '3')]),
        ),
    ]
